apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
     name: my-cluster-role1
roleRef:
     apiGroup: rbac.authorization.k8s.io
     kind: ClusterRole
     name: my-cluster-role1
subjects:
   - kind: ServiceAccount
     name: my-sa
     namespace : my-ns
