apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
   name: my-cluster-role1
rules:
 - apiGroups:
         - "*"
   resources:
         - deployments
         - services
   verbs:
         - get
         - list
