apiVersion: v1
kind: Pod
metadata:
      name: cpu-mem-quota
spec: 
      containers:
            - name: nginx
              image: nginx
              resources: 
                  requests: 
                     memory: "128Mi"
                     cpu : 0.5
                  limits: 
                     memory: "256Mi"
                     cpu: 0.8
