apiVersion: apps/v1
kind: Deployment
metadata: 
    name: app-headless
    labels:
          app: my-app-headless
spec:
    replicas: 2    
    selector:
          matchLabels: 
               app: my-app-headless
    template:
          metadata:
               labels:          
                    app: my-app-headless
          spec:
               containers:
                  - name: nginx
                    image: nginx:1.16
                    ports:
                    - containerPort: 80
                     
                            
                   
        
