apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
   name: my-role 
   namespace: my-ns
rules:  
   - apiGroups: 
	- "*"
     resources: 
	- pods
	- services 
     verbs:
        - get 
        - list
