apiVersion: v1
kind: Pod 
metadate: 
      name: with-node-affinity
      labels: 
         env: test
spec: 
      containers:
         - name: nginx 
           image: nginx 
      affinity:
              nodeAffinity: 
	       requiredDuringSchedulingIgnoredDuringExecution:
	        nodeSelectorTerms:
	        - matchExpressions:
         	  - key: env
	            operator: In
	            values: 
                       - test
                         test1
